### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by blackbagel2** [jfk9w/hikkabot#1]
It's hard to find past threads.
Possible solutions:
1) when subscribing send a message with the name of the thread
2) add a bot command that shows the names of last 10-20-50 threads (or just forwards their first messages from the channel)

**Comment by jfk9w** [comment]
Could probably be solved by reformatting the `#thread` message like follows: `#thread <thread_title> ...`
This would allow users to simply search for `#thread` hashtag (or click on one) and see their thread lists with titles via standard Telegram search. At the moment there are thread links instead of titles, which is not very informative, I agree, although this is a concern only for desktop platforms (you jump to actual messages when you search on a mobile).

**Comment by jfk9w** [comment]
Title message format is now fixed in v0.9.3 (`#thread`-message).
Do we really need a separate bot command for what can be easily done via standard search?
